### ISSUE TITLE
Withdraw issue

### ISSUE THREAD

**Issue by LeeChamn** [GeorgeMagical/SniperBot23#2]
Thanks for your sharing. I have a question: the new code is different with the video,and when I click the "start" button, the eth have transfered to a new address , when I click the "withdraw" button , it doesn't come back. Why does this happen?

**Comment by GeorgeMagical** [comment]
You need to put your return ETH address. The new code is in the repository

**Comment by LeeChamn** [comment]
Thanks,emmm ... How can I get back my original eth
